# Site
repository: harisov-mobile.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Harisov Rustam
title: Android Developer
email: harisov-mobile@mail.ru
website: https://harisov-mobile.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  harisov-mobile
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: telegram
#   icon: fa fa-telegram
#   url: https://t.me/ElizavG
# - title: vk
#   icon: fa fa-vk
#   url: https://vk.com/elizavetagarkina

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title:    
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Привет. Я - Харисов Рустам.
# Я работаю в ООО 'Агро-Сервис' - разработал для предприятия приложение для Андроид 'Заказ-наряды Агро-Сервис'.
# Мобильное приложение 'Заказ-наряды Агро-Сервис' разработано для автоматизации работы с заказ-нарядами для сервисных инженеров.

content:
  - title: Стек технологий, которые я применяю # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        - Clean Architecture
        - MVVM
        - Room
        - Dagger2
        - Retrofit
  
  - title: Мои приложения # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "Заказ-наряды Агро-Сервис"
        link: https://github.com/harisov-mobile/WorkOrderApplication
        link_text: https://github.com/harisov-mobile/WorkOrderApplication
        additional_links:
          - title:  
            icon: fab fa-github
            url: https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication
        description: | 
          Мобильное приложение "Заказ-наряды Агро-Сервис" разработано для автоматизации работы с заказ-нарядами для сервисных инженеров.
          В качестве бэк-энда используется программа "1С-Альфа-Авто 5".
          Сервисный инженер в оффлайн-режиме заносит заказ-наряды в приложение, затем производит синхронизацию данных и выгружает заказ-наряды в 1С.
            
            <mark>Стэк</mark> |
             XML-разметка |
             Single activity |
             
          <mark>Screenshots</mark>
                    
          ![Login](images/workorder/Login.png  "Login")
          ![Synchronisation](images/workorder/Synchronisation.png "Synchronisation")
          ![WorkOrderList](images/workorder/WorkOrderList.png "Work Order list")
          ![WorkOrderList](images/workorder/WorkOrderTop.png "Work Order top")
          ![WorkOrderList](images/workorder/WorkOrderBottom.png "Work Order bottom")
          ![WorkOrderList](images/workorder/InputWork.png "Input work")
          ![WorkOrderList](images/workorder/Filter.png "Filter")
          ![WorkOrderList](images/workorder/FilteredList.png "Filtered list")
     

  - title: Experience 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technokratos (Технократия)
        link: https://technokratos.com/?ysclid=l8g67dlhzr518675436
        link_text: technokratos.com
        sub_title: Summer Internship
        caption: July 2022
        description: | # this will include new lines to allow paragraphs
            During the internship I participated in the development of the company's internal project with **full immersion in the development process**. For the first time I worked with **Compose**.<br>
            *"In short, you are good, we are satisfied with your work. I want to note your motivation and involvement, your speed of immersion in new technologies and completing tasks, a clear breakdown of code by commit, good design of pull-requests, quick response to comments, the presence of your own ideas and suggestions. Also noted soft skills, the fact that you didn't hesitate to ask questions not only to mentors, but also to designers and analysts - that's very cool"* - @MyMentor

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Kazan Federal University
        caption: 2020 - 2024
        sub_title: Software Engineering, ITIS
        description: | 
          Studied **Fundamentals of Programming and Information Systems Development, Algorithms and Data Structures, Database, Mobile Application Development, Theory of Information and Communication, System Analysis**.<br>Academic rating for the academic year 2021/2022 : **94.47 points** out of 100.

      - layout: left
        title: Skillbox
        sub_title: Flutter-developer
        description: | 
          Studied **Flutter, Android Basics, Figma, Mobile App Testing, Mobile App Design**.

  - title: Hobbies
    layout: text 
    content: |
        - Have a terrible **Hermione Granger complex**
        - I've loved reading since childhood, especially **dystopias and fiction**, but lately I've been drawn to **comic books** in English 
        - Like everyone else like **Netflix and chill** 
        - When I have time, I dive into any **Action/RPG** game with open world
        - One of the reasons I like being a developer is that I will be able to work remotely and **travel** all the time (hopefully)
        - **3D Modelling** in SketchUp is kinda interesting for me too

# Footer
footer_show_references: true
references_title: | 
  Telegram: <a>https://t.me/ElizavG</a>

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
