# Site
repository: harisov-mobile.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Harisov Rustam
title: Android Developer
email: harisov.mobile@gmail.com
website: https://harisov-mobile.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  harisov-mobile
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
 - title: telegram
   icon: fa fa-telegram
   url: https://t.me/mob_dev_mob
# - title: vk
#   icon: fa fa-vk
#   url: https://vk.com/elizavetagarkina

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <br>   
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Привет. Я - Харисов Рустам,  мобильный разработчик, работаю в ООО "Агро-Сервис", г.Казань.<br>
 Разработал для предприятия мобильное приложение для Андроид "Заказ-наряды Агро-Сервис",<br>
 которое позволяет автоматизировать работу сервисных инженеров:<br>
 сервисные инженеры в оффлайн-режиме заносят заказ-наряды в приложение, затем производят синхронизацию данных и выгружают заказ-наряды в 1С.


content:
  - title: Стек технологий, которые я применяю # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        - XML-верстка и Compose
        - Coroutines
        - MVVM
        - MVIKotlin
        - Room
        - Retrofit
        - Koin
        - Dagger2
        - AppAuth (авторизация по стандарту OAuth 2.0) 
        - Clean Architecture<br><br>
        
              
  
  - title: Мои приложения # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "Заказ-наряды Агро-Сервис"
        link: https://github.com/harisov-mobile/WorkOrderApplication
        link_text: https://github.com/harisov-mobile/WorkOrderApplication

        description: | 
          Мобильное приложение "Заказ-наряды Агро-Сервис" разработано для автоматизации работы с заказ-нарядами для сервисных инженеров.<br>
          В качестве бэк-энда используется программа "1С-Альфа-Авто 5".<br>
          Сервисный инженер в оффлайн-режиме заносит заказ-наряды в приложение, затем производит синхронизацию данных и выгружает заказ-наряды в 1С.<br>
          <br>
          Приложение опубликовано в <a href="https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication">Гугл Плей Маркете</a>
        
            <mark>Стэк</mark> |
             XML-разметка |
             Single activity |
             Single module |
             Coroutines |
             MVVM |
             Room |
             Retrofit |
             Dagger2 |
             Clean Architecture |
        
          <mark>Screenshots</mark>
                    
          ![Login](images/workorder/Login.png  "Login")
          ![Synchronisation](images/workorder/Synchronisation.png "Synchronisation")
          ![WorkOrderList](images/workorder/WorkOrderList.png "Work Order list")
          ![WorkOrderList](images/workorder/WorkOrderTop.png "Work Order top")
          ![WorkOrderList](images/workorder/WorkOrderBottom.png "Work Order bottom")
          ![WorkOrderList](images/workorder/InputWork.png "Input work")
          ![WorkOrderList](images/workorder/Filter.png "Filter")
          ![WorkOrderList](images/workorder/FilteredList.png "Filtered list")
     

      - layout: top-middle
        title: "Где я?"
        link: https://github.com/harisov-mobile/WhereAmI
        link_text: https://github.com/harisov-mobile/WhereAmI

        description: | 
          Приложение "Где я?" показывает Ваше текущее местоположение на карте.<br>
          Приложение может показать маршрут от Вашего местоположения до выбранной точки на карте.<br>
          Маршрут можно показать для пешехода, для велосипедиста или для автомобиля.<br><br>
          В качестве картографического сервиса используется OpenStreetMap, библиотека Osmdroid.<br>
          <br>
          Приложение опубликовано в <a href="https://play.google.com/store/apps/details?id=ru.internetcloud.whereami">Гугл Плей Маркете</a>
        
            <mark>Стэк</mark> |
             XML-разметка |
             Single activity |
             Single module |
             Coroutines |
             MVVM |
             Dagger2 |
             Clean Architecture |
             Osmdroid |
        
          <mark>Screenshots</mark>
                    
          ![Splashscreen](images/whereami/Splashscreen.png  "Splashscreen")
          ![BogginiPark](images/whereami/BogginiPark.png "BogginiPark")
          ![Address](images/whereami/Address.png "Address")
          ![Foot](images/whereami/Foot.png "Foot")
          ![Bike](images/whereami/Bike.png "Bike")
          ![Car](images/whereami/Car.png "Car")

      - layout: top-middle
        title: "My Strava"
        link: https://github.com/harisov-mobile/kts-2023-strava-app
        link_text: https://github.com/harisov-mobile/kts-2023-strava-app
        
        description: | 
          Приложение "My Strava" - клиент для сервиса Strava.<br>
          Strava - это сервис для отслеживания активности спортсменов с помощью мобильных устройств и социальная сеть для спортсменов,<br>
          где спортсмены могут сравнивать свои результаты, ставить цели, общаться и т. д.
          <br>
          Функционал приложения:<br>
          Для пользователя, который авторизовался в приложении с помощью аккаунта Strava:<br>
          - Просмотр тренировок пользователя;<br>
          - Просмотр детальной информации о тренировке;<br>
          - Добавление новой тренировки пользователя или редактирование существующей тренировки;<br>
          - Просмотр информации о профиле пользователя;<br>
          - Оффлайн-режим;<br>
          - Логаут (выход из аккаунта пользователя).<br>
          <br>
                  
            <mark>Стэк</mark> |
             XML-разметка & Compose |
             Single activity |
             Single module |
             Coroutines |
             MVVM |
             MVI Kotlin |
             Room |
             Retrofit |
             AppAuth (авторизация по стандарту OAuth 2.0) |
             Koin |
             Clean Architecture |
        
          <mark>Screenshots</mark>
                    
          ![OnBoarding](images/mystrava/OnBoarding.png  "OnBoarding")
          ![Training_list](images/mystrava/Training_list.png "Training list")
          ![Training_detail](images/mystrava/Training_detail.png "Training detail")
          ![Training_edit](images/mystrava/Training_edit.png "Training edit")
          ![Sport_picker](images/mystrava/Sport_picker.png "Sport picker")
          ![Date_picker](images/mystrava/Date_picker.png "Date_picker")
          ![Time_picker](images/mystrava/Time_picker.png "Time_picker")
          ![Duration_picker](images/mystrava/Duration_picker.png "Duration_picker")
          ![Profile](images/mystrava/Profile.png "Profile")
          ![Logout](images/mystrava/Logout.png "Logout")

     

  - title: Опыт работы 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ООО "Агро-Сервис"
        sub_title: Андроид разработчик
        caption: 2022 - по настоящее время
        description: | # this will include new lines to allow paragraphs
            Разработал мобильное приложение для Андроид "Заказ-наряды Агро-Сервис" для автоматизации работы с заказ-нарядами для сервисных инженеров.<br>
            Ссылка на приложение в Гугл Плей Маркете: <a href="https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication">Work Order Application</a>
            
      - layout: left
        title: Различные организации
        sub_title: Программист 1С
        caption: 2012 - 2022
        description: | # this will include new lines to allow paragraphs
            Доработки конфигураций 1С УТ10.3, Альфа-Авто-5, БП 3.0 под задачи предприятия, создание двустороннего обмена между УТ10.3 и веб-сайтом предприятия на HTTP-сервисах (REST).<br>
            Создание различных печатных форм, отчетов, обработок для 1С, правил конвертации для КД 2.0 для обменов и т.д. и т.п. <br>
            На одном из предприятий удалось поработать по методике Agile со спринтами, ретроспективами, "покером", стори-поинтами и т.д. <br>

      - layout: left
        title: Различные организации
        sub_title: Инженер-программист
        caption: 2008 - 2012
        description: | # this will include new lines to allow paragraphs
            Доработка существующих программ на FoxPro.<br>
            Создание небольших программ для внутренних нужд предприятия на Delphi.<br>
            Доработка программ на Visual Basic for Access.<br>
            Интеграция между существующими на предприятии базами данных MS SQL Server, MS Access и 1С:УПП 8.1.<br>


  - title: Образование 
    layout: list 
    content:
      - layout: left
        title: Казанский государственный технический университет имени А.Н.Туполева (КАИ)
        caption: 2002 - 2008
        sub_title: Инженер по автоматизированным системам управления
        description: | 
          Факультет технической кибернетики и информатики. Кафедра Автоматизированных Систем Обработки Информации и Управления.



  - title: Хобби
    layout: text 
    content: |
        - Велосипед. 

# Footer
footer_show_references: true
references_title: | 
  

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
