# Site
repository: harisov-mobile.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Harisov Rustam
title: Android Developer
email: harisov-mobile@mail.ru
website: https://harisov-mobile.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  harisov-mobile
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: telegram
#   icon: fa fa-telegram
#   url: https://t.me/ElizavG
# - title: vk
#   icon: fa fa-vk
#   url: https://vk.com/elizavetagarkina

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <br>   
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Привет. Я - Харисов Рустам, работаю в ООО "Агро-Сервис" - как программист 1С и еще немного как мобильный разработчик.<br>
 Разработал для предприятия мобильное приложение для Андроид "Заказ-наряды Агро-Сервис",<br>
 которое позволяет автоматизировать работу сервисных инженеров:<br>
 сервисные инженеры в оффлайн-режиме заносят заказ-наряды в приложение, затем производят синхронизацию данных и выгружают заказ-наряды в 1С.


content:
  - title: Стек технологий, которые я применяю # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        - Clean Architecture
        - MVVM
        - Room
        - Dagger2
        - Retrofit
    description: |
      В настоящее время также изучаю технологии: Compose, KMM         
  
  - title: Мои приложения # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "Заказ-наряды Агро-Сервис"
        link: https://github.com/harisov-mobile/WorkOrderApplication
        link_text: https://github.com/harisov-mobile/WorkOrderApplication
        additional_links:
            link:  https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication
            link_text:  https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication
          #- title: https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication 
          #  icon: fab fa-google
          #  url: https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication
        description: | 
          Мобильное приложение "Заказ-наряды Агро-Сервис" разработано для автоматизации работы с заказ-нарядами для сервисных инженеров.<br>
          В качестве бэк-энда используется программа "1С-Альфа-Авто 5".<br>
          Сервисный инженер в оффлайн-режиме заносит заказ-наряды в приложение, затем производит синхронизацию данных и выгружает заказ-наряды в 1С.<br>
          <br>
          Приложение опубликовано в Гугл Плей Маркете: <a href="https://play.google.com/store/apps/details?id=ru.internetcloud.workorderapplication">
<img src="/screenshots/GooglePlay.png" alt="Get it on Play Market" height="70"></a>
        

            
            <mark>Стэк</mark> |
             XML-разметка |
             Single activity |
             Single module |
             Clean Architecture |
             MVVM |
             Room |
             Retrofit |
             Dagger2 |
             Coroutines |
        
             
          <mark>Screenshots</mark>
                    
          ![Login](images/workorder/Login.png  "Login")
          ![Synchronisation](images/workorder/Synchronisation.png "Synchronisation")
          ![WorkOrderList](images/workorder/WorkOrderList.png "Work Order list")
          ![WorkOrderList](images/workorder/WorkOrderTop.png "Work Order top")
          ![WorkOrderList](images/workorder/WorkOrderBottom.png "Work Order bottom")
          ![WorkOrderList](images/workorder/InputWork.png "Input work")
          ![WorkOrderList](images/workorder/Filter.png "Filter")
          ![WorkOrderList](images/workorder/FilteredList.png "Filtered list")
     

  - title: Опыт работы 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ООО "Агро-Сервис"
        sub_title: Программист 1С
        caption: Май 2020 - по настоящее время
        description: | # this will include new lines to allow paragraphs
            Помимо доработок конфигураций 1С разработал мобильное приложение для Андроид "Заказ-наряды Агро-Сервис" для автоматизации работы с заказ-нарядами для сервисных инженеров.<br>
            
      - layout: left
        title: Различные организации
        sub_title: Программист 1С
        caption: 2009 - 2020
        description: | # this will include new lines to allow paragraphs
            Доработки конфигураций 1С УТ10.3, Альфа-Авто-5, БП 3.0 под задачи предприятия, создание двустороннего обмена между УТ10.3 и веб-сайтом предприятия на HTTP-сервисах (REST).<br>
            Создание различных печатных форм, отчетов, обработок для 1С, правил конвертации для КД 2.0 для обменов и т.д. и т.п. <br>
            На одном из предприятий удалось поработать по методике Agile со спринтами, ретроспективами, "покером", стори-поинтами и т.д. <br>

      - layout: left
        title: Различные организации
        sub_title: Инженер-программист
        caption: 1998 - 2009
        description: | # this will include new lines to allow paragraphs
            Доработка существующих программ на FoxPro.<br>
            Создание небольших программ для внутренних нужд предприятия на Delphi.<br>
            Доработка программ на Visual Basic for Access.<br>
            Интеграция между существующими на предприятии базами данных MS SQL Server, MS Access и 1С:УПП 8.1.<br>


  - title: Образование 
    layout: list 
    content:
      - layout: left
        title: Казанский государственный технический университет имени А.Н.Туполева
        caption: 1992 - 1998
        sub_title: Инженер-системотехник по автоматизированным системам управления
        description: | 
          Факультет технической кибернетики и информатики. Кафедра Автоматизированных Систем Обработки Информации и Управления.



  - title: Хобби
    layout: text 
    content: |
        - Велосипед: с удовольствием катаюсь по парку. 

# Footer
footer_show_references: true
references_title: | 
  

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
